---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19.2

inputs:
  - name: dp-dimension-extractor
    path: dp-dimension-extractor

outputs:
  - name: build

run:
  path: dp-dimension-extractor/ci/scripts/build.sh
