---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.10.0

inputs:
  - name: dp-dimension-extractor
    path: go/src/github.com/ONSdigital/dp-dimension-extractor

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-dimension-extractor/ci/scripts/build.sh
