// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package testcodelist

import (
	"context"
	"net/http"
	"sync"
)

var (
	lockImportClientMockDo sync.RWMutex
)

// ImportClientMock is a mock implementation of ImportClient.
//
//     func TestSomethingThatUsesImportClient(t *testing.T) {
//
//         // make and configure a mocked ImportClient
//         mockedImportClient := &ImportClientMock{
//             DoFunc: func(ctx context.Context, req *http.Request) (*http.Response, error) {
// 	               panic("TODO: mock out the Do method")
//             },
//         }
//
//         // TODO: use mockedImportClient in code that requires ImportClient
//         //       and then make assertions.
//
//     }
type ImportClientMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, req *http.Request) (*http.Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *http.Request
		}
	}
}

// Do calls DoFunc.
func (mock *ImportClientMock) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	if mock.DoFunc == nil {
		panic("moq: ImportClientMock.DoFunc is nil but ImportClient.Do was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *http.Request
	}{
		Ctx: ctx,
		Req: req,
	}
	lockImportClientMockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	lockImportClientMockDo.Unlock()
	return mock.DoFunc(ctx, req)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//     len(mockedImportClient.DoCalls())
func (mock *ImportClientMock) DoCalls() []struct {
	Ctx context.Context
	Req *http.Request
} {
	var calls []struct {
		Ctx context.Context
		Req *http.Request
	}
	lockImportClientMockDo.RLock()
	calls = mock.calls.Do
	lockImportClientMockDo.RUnlock()
	return calls
}
